[tool.poetry]
name = "space-invaders"
version = "0.1.0"
description = ""
authors = ["Kaushik"]

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^1.9.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
